#!/usr/bin/env python3
"""Sync PurpleShire.uk front-page blocks and LIAF landings from Google Drive.

For each block in front-page-blocks/ and each LIAF landing
(liaf-landings/en|ru/<slug>.html), compares the Drive file's modifiedTime
against the last-synced value recorded in .drive_ids.json. Files that are
newer on Drive are downloaded (overwriting the local copy); front-page
blocks trigger assemble.py / assemble_ru.py, and everything changed is
pushed to GitHub (Carl-Walker-pm.github.io).

Drive -> local wins on every sync. NOTE: the 3 LIAF landings without
originals (praw-mutual, lunar-mall, aed-project) are regenerated by
generate.py from projects.json — a Drive edit there survives until the
next generate.py run. The 13 original-based landings are only ever rebuilt
by build_liaf.py, so Drive edits to them are safe.

Idempotent: when nothing changed on Drive, the script prints nothing and
exits 0 (safe for an hourly cron). Any action is logged to stdout.

Usage: python3 sync_blocks.py
"""

import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone

BASE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.dirname(BASE)
INDEX = os.path.join(BUILD, "purpleshireuk", "index.html")
RU_INDEX = os.path.join(BUILD, "purpleshireuk", "ru", "index.html")
STATE = os.path.join(BASE, ".drive_ids.json")
ASSEMBLE = os.path.join(BASE, "assemble.py")
ASSEMBLE_RU = os.path.join(BASE, "assemble_ru.py")
PUBLISH = "/home/hatch/workspace/skills/github/bin/publish_dir.py"
STAGING = os.path.join(BUILD, ".push-staging")

OWNER = "Carl-Walker-pm"
REPO = "Carl-Walker-pm.github.io"
REPO_PATHS = ["purpleshireuk/index.html", "purpleshireuk/ru/index.html"]

# All 16 LIAF slugs, in Drive as liaf-landings/en|ru/<slug>.html.
LIAF_SLUGS = [
    "aura-botanica", "aurelius", "future-proof-travel", "kinetic", "lumina",
    "proso", "selene", "softhouse", "synthetix", "tao-school",
    "unity-travel", "vantage", "velocity",
    "praw-mutual", "lunar-mall", "aed-project",
]
PROJECTS_DIR = os.path.join(BUILD, "purpleshireuk", "projects")
RU_PROJECTS_DIR = os.path.join(BUILD, "purpleshireuk", "ru", "projects")


def landing_local_path(key):
    """Map a liaf-landings/<lang>/<slug>.html state key to its local file."""
    parts = key.split("/")
    lang, fname = parts[1], parts[2]
    slug = fname[:-5]  # strip .html
    base = PROJECTS_DIR if lang == "en" else RU_PROJECTS_DIR
    return os.path.join(base, slug, "index.html")


def drive(*args):
    r = subprocess.run(["hatch_gws_cli", "drive"] + list(args),
                       capture_output=True, text=True, timeout=120)
    return r


def parse_ts(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def main():
    with open(STATE, encoding="utf-8") as f:
        state = json.load(f)

    changed_en = []
    changed_ru = []
    changed_landings = []  # (state key, repo-relative path) pairs
    for name in sorted(state):
        fid = state[name]["id"]
        last = parse_ts(state[name]["modifiedTime"])
        r = drive("files", "get", "--params",
                  json.dumps({"fileId": fid, "fields": "id,name,modifiedTime"}))
        if r.returncode != 0:
            print("WARN: could not read Drive metadata for %s: %s"
                  % (name, r.stderr.strip()[:200]))
            continue
        try:
            meta = json.loads(r.stdout)
        except Exception:
            print("WARN: bad Drive response for %s" % name)
            continue
        remote = parse_ts(meta["modifiedTime"])
        if remote > last:
            if name.startswith("liaf-landings/"):
                local = landing_local_path(name)
            else:
                local = os.path.join(BASE, name)
            os.makedirs(os.path.dirname(local), exist_ok=True)
            d = drive("files", "get", "--params",
                      json.dumps({"fileId": fid, "alt": "media"}),
                      "--output", local)
            if d.returncode != 0:
                print("WARN: download failed for %s: %s"
                      % (name, d.stderr.strip()[:200]))
                continue
            state[name]["modifiedTime"] = meta["modifiedTime"]
            if name.startswith("liaf-landings/"):
                repo_rel = os.path.relpath(local, BUILD)
                changed_landings.append((name, repo_rel))
            else:
                (changed_ru if name.startswith("ru/") else changed_en).append(name)

    if not changed_en and not changed_ru and not changed_landings:
        return  # silent: nothing to do

    for name in changed_en + changed_ru:
        print("pulled %s from Drive" % name)
    for name, _rel in changed_landings:
        print("pulled %s from Drive" % name)
    with open(STATE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)

    if changed_en:
        run_assemble(ASSEMBLE, "EN")
    if changed_ru:
        run_assemble(ASSEMBLE_RU, "RU")

    push_all([rel for _name, rel in changed_landings])


def run_assemble(script, label):
    a = subprocess.run([sys.executable, script], capture_output=True,
                       text=True, timeout=120)
    print(a.stdout.strip() or "%s: no output" % os.path.basename(script))
    if a.returncode != 0:
        print("ERROR: %s (%s) failed:\n%s"
              % (label, os.path.basename(script), a.stderr.strip()[:1000]))
        sys.exit(1)


def push_all(landing_rels):
    """Push rebuilt index.html files and any changed LIAF landings to GitHub.
    Logs the outcome; a 403 from a read-only credential is reported plainly,
    not raised as an error."""
    staged = []
    pairs = [(INDEX, "purpleshireuk/index.html"),
             (RU_INDEX, "purpleshireuk/ru/index.html")]
    for rel in landing_rels:
        pairs.append((os.path.join(BUILD, rel), rel))
    for src, rel in pairs:
        if not os.path.isfile(src):
            continue
        dest = os.path.join(STAGING, rel)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        shutil.copy2(src, dest)
        staged.append(rel)
    msg = "front-page blocks + LIAF landings: sync from Drive"
    r = subprocess.run([sys.executable, PUBLISH, OWNER, REPO, STAGING, msg],
                       capture_output=True, text=True, timeout=300)
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode == 0:
        print("GitHub push OK: %s -> %s" % (
            ", ".join(staged),
            r.stdout.strip().splitlines()[-1] if r.stdout.strip() else "committed"))
    else:
        tail = "\n".join(out.strip().splitlines()[-6:])
        if "403" in out or "Resource not accessible" in out:
            print("GitHub push BLOCKED (403): the stored credential cannot write "
                  "to %s/%s. index.html is staged at %s and will push once a "
                  "write-capable token lands.\n%s" % (OWNER, REPO, STAGING, tail))
        else:
            print("GitHub push FAILED (exit %d):\n%s" % (r.returncode, tail))


if __name__ == "__main__":
    main()
